### ISSUE TITLE
Problem accessing when running as docker container

### ISSUE THREAD

**Issue by davejhahn** [ai-dock/kohya_ss#7]
I'm running on Ubuntu, starts up fine, says listening on 17860, I expose in a docker-compose.yml, but I can't access with http://<my_local_ip>:17860

It says: To create a public link, set `share=True` in `launch()`.

So I'm thinking this needs to be set?  Not sure how to do this since I'm running the image.

My docker-compose.yml:

```
services:
  koya_ss:
    image: ghcr.io/ai-dock/kohya_ss:v2-cuda-12.1.1-base-22.04-sd3-flux.1
    #image: koya_ss:installed
    ports:
      - "17860:17860"
    volumes:
      - /photoshop/assets:/photoshop/assets

```

Any suggestions?

Thanks.
